[package]
name = "deepseekinrust"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.217"
tch = "0.19.0"
tokio = "1.43.0"
cudarc = { version = "0.13.4", features = ["cuda-12060"]}
cust = "0.3.2"

[build-dependencies]
cc = "1.0"